url: https://fallible.co   # with the https protocol
enforce_ssl: fallible.co   # without any protocol

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

markdown:    kramdown
highlighter: pygments

# Setup
title:               Fallible Blog
tagline:             'Adventures with looking under the hood'
description:         'We discover bugs, disclose them responsibly, help companies fix them and then write about them here. Companies that have a non-disclosure plan with us are not mentioned here.'
url:                 http://fallible.co/blog
baseurl:             '/blog'
paginate:            10

# About/contact
author:
  name:              Fallible
  url:               https://twitter.com/fallible_inc
  email:             hello@fallible.co
